version: '2'

services:
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - laravel-education-db:/var/lib/mysql
    ports:
      - 3307:3306
    entrypoint:
      sh -c "
      echo 'CREATE DATABASE IF NOT EXISTS laravel_db;' > /docker-entrypoint-initdb.d/init.sql;
      /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "
    networks:
      - laravel-education-net

  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ./app:/var/www/app
    depends_on:
      - mysql
    networks:
      - laravel-education-net

  nginx:
    build:
      context: docker/nginx
    volumes:
      - ./app:/var/www/app
    depends_on:
      - php-fpm
    ports:
      - 8085:80
    networks:
      - laravel-education-net

networks:
  laravel-education-net:

volumes:
  laravel-education-db:
